///
//  Generated code. Do not modify.
//  source: healthdata.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type

const HealthTypes$json = const {
  '1': 'HealthTypes',
  '2': const [
    const {'1': 'WORKOUT_MAIN', '2': 0},
    const {'1': 'CATEGORY_SLEEP_ANALYSIS', '2': 1},
    const {'1': 'CATEGORY_APPLE_STAND_HOUR', '2': 2},
    const {'1': 'CATEGORY_CERVICAL_MUCUS_QUALITY', '2': 3},
    const {'1': 'CATEGORY_OVULATION_TEST_RESULT', '2': 4},
    const {'1': 'CATEGORY_MENSTRUAL_FLOW', '2': 5},
    const {'1': 'CATEGORY_INTERMENSTRUAL_BLEEDING', '2': 6},
    const {'1': 'CATEGORY_SEXUAL_ACTIVITY', '2': 7},
    const {'1': 'CATEGORY_MINDFUL_SESSION', '2': 8},
    const {'1': 'CATEGORY_HIGH_HEART_RATE_EVENT', '2': 9},
    const {'1': 'CATEGORY_LOW_HEART_RATE_EVENT', '2': 10},
    const {'1': 'CATEGORY_IRREGULAR_HEART_RHYTHM_EVENT', '2': 11},
    const {'1': 'QUANTITY_BODY_MASS_INDEX', '2': 12},
    const {'1': 'QUANTITY_BODY_FAT_PERCENTAGE', '2': 13},
    const {'1': 'QUANTITY_HEIGHT', '2': 14},
    const {'1': 'QUANTITY_BODY_MASS', '2': 15},
    const {'1': 'QUANTITY_LEAN_BODY_MASS', '2': 16},
    const {'1': 'QUANTITY_STEP_COUNT', '2': 17},
    const {'1': 'QUANTITY_DISTANCE_WALKING_RUNNING', '2': 18},
    const {'1': 'QUANTITY_DISTANCE_CYCLING', '2': 19},
    const {'1': 'QUANTITY_BASAL_ENERGY_BURNED', '2': 20},
    const {'1': 'QUANTITY_ACTIVE_ENERGY_BURNED', '2': 21},
    const {'1': 'QUANTITY_FLIGHTS_CLIMBED', '2': 22},
    const {'1': 'QUANTITY_NIKE_FUEL', '2': 23},
    const {'1': 'QUANTITY_HEART_RATE', '2': 24},
    const {'1': 'QUANTITY_BODY_TEMPERATURE', '2': 25},
    const {'1': 'QUANTITY_BASAL_BODY_TEMPERATURE', '2': 26},
    const {'1': 'QUANTITY_BLOOD_PRESSURE_SYSTOLIC', '2': 27},
    const {'1': 'QUANTITY_BLOOD_PRESSURE_DIASTOLIC', '2': 28},
    const {'1': 'QUANTITY_RESPIRATORY_RATE', '2': 29},
    const {'1': 'QUANTITY_OXYGEN_SATURATION', '2': 30},
    const {'1': 'QUANTITY_PERIPHERAL_PERFUSION_INDEX', '2': 31},
    const {'1': 'QUANTITY_BLOOD_GLUCOSE', '2': 32},
    const {'1': 'QUANTITY_NUMBER_OF_TIMES_FALLEN', '2': 33},
    const {'1': 'QUANTITY_ELECTRODERMAL_ACTIVITY', '2': 34},
    const {'1': 'QUANTITY_INHALER_USAGE', '2': 35},
    const {'1': 'QUANTITY_BLOOD_ALCOHOL_CONTENT', '2': 36},
    const {'1': 'QUANTITY_FORCED_VITAL_CAPACITY', '2': 37},
    const {'1': 'QUANTITY_FORCED_EXPIRATORY_VOLUME1', '2': 38},
    const {'1': 'QUANTITY_PEAK_EXPIRATORY_FLOW_RATE', '2': 39},
    const {'1': 'QUANTITY_DIETARY_FAT_TOTAL', '2': 40},
    const {'1': 'QUANTITY_DIETARY_FAT_POLYUNSATURATED', '2': 41},
    const {'1': 'QUANTITY_DIETARY_FAT_MONOUNSATURATED', '2': 42},
    const {'1': 'QUANTITY_DIETARY_FAT_SATURATED', '2': 43},
    const {'1': 'QUANTITY_DIETARY_CHOLESTEROL', '2': 44},
    const {'1': 'QUANTITY_DIETARY_SODIUM', '2': 45},
    const {'1': 'QUANTITY_DIETARY_CARBOHYDRATES', '2': 46},
    const {'1': 'QUANTITY_DIETARY_FIBER', '2': 47},
    const {'1': 'QUANTITY_DIETARY_SUGAR', '2': 48},
    const {'1': 'QUANTITY_DIETARY_ENERGY_CONSUMED', '2': 49},
    const {'1': 'QUANTITY_DIETARY_PROTEIN', '2': 50},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_A', '2': 51},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_B6', '2': 52},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_B12', '2': 53},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_C', '2': 54},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_D', '2': 55},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_E', '2': 56},
    const {'1': 'QUANTITY_DIETARY_VITAMIN_K', '2': 57},
    const {'1': 'QUANTITY_DIETARY_CALCIUM', '2': 58},
    const {'1': 'QUANTITY_DIETARY_IRON', '2': 59},
    const {'1': 'QUANTITY_DIETARY_THIAMIN', '2': 60},
    const {'1': 'QUANTITY_DIETARY_RIBOFLAVIN', '2': 61},
    const {'1': 'QUANTITY_DIETARY_NIACIN', '2': 62},
    const {'1': 'QUANTITY_DIETARY_FOLATE', '2': 63},
    const {'1': 'QUANTITY_DIETARY_BIOTIN', '2': 64},
    const {'1': 'QUANTITY_DIETARY_PANTOTHENIC_ACID', '2': 65},
    const {'1': 'QUANTITY_DIETARY_PHOSPHORUS', '2': 66},
    const {'1': 'QUANTITY_DIETARY_IODINE', '2': 67},
    const {'1': 'QUANTITY_DIETARY_MAGNESIUM', '2': 68},
    const {'1': 'QUANTITY_DIETARY_ZINC', '2': 69},
    const {'1': 'QUANTITY_DIETARY_SELENIUM', '2': 70},
    const {'1': 'QUANTITY_DIETARY_COPPER', '2': 71},
    const {'1': 'QUANTITY_DIETARY_MANGANESE', '2': 72},
    const {'1': 'QUANTITY_DIETARY_CHROMIUM', '2': 73},
    const {'1': 'QUANTITY_DIETARY_MOLYBDENUM', '2': 74},
    const {'1': 'QUANTITY_DIETARY_CHLORIDE', '2': 75},
    const {'1': 'QUANTITY_DIETARY_POTASSIUM', '2': 76},
    const {'1': 'QUANTITY_DIETARY_CAFFEINE', '2': 77},
    const {'1': 'QUANTITY_DIETARY_WATER', '2': 78},
    const {'1': 'QUANTITY_UV_EXPOSURE', '2': 79},
    const {'1': 'QUANTITY_APPLE_EXERCISE_TIME', '2': 80},
    const {'1': 'QUANTITY_DISTANCE_WHEELCHAIR', '2': 81},
    const {'1': 'QUANTITY_PUSH_COUNT', '2': 82},
    const {'1': 'QUANTITY_DISTANCE_SWIMMING', '2': 83},
    const {'1': 'QUANTITY_SWIMMING_STROKE_COUNT', '2': 84},
    const {'1': 'QUANTITY_WAIST_CIRCUMFERENCE', '2': 85},
    const {'1': 'QUANTITY_VO2_MAX', '2': 86},
    const {'1': 'QUANTITY_RESTING_HEART_RATE', '2': 87},
    const {'1': 'QUANTITY_WALKING_HEART_RATE_AVERAGE', '2': 88},
    const {'1': 'QUANTITY_HEART_RATE_VARIABILITY_SDNN', '2': 89},
    const {'1': 'QUANTITY_INSULIN_DELIVERY', '2': 90},
    const {'1': 'QUANTITY_DISTANCE_DOWNHILL_SNOW_SPORTS', '2': 91},
    const {'1': 'CHARACTERISTIC_BIOLOGICAL_SEX', '2': 92},
    const {'1': 'CHARACTERISTIC_BLOOD_TYPE', '2': 93},
    const {'1': 'CHARACTERISTIC_DATE_OF_BIRTH', '2': 94},
    const {'1': 'CHARACTERISTIC_FITZPATRICK_SKIN_TYPE', '2': 95},
    const {'1': 'CHARACTERISTIC_WHEELCHAIR_USE', '2': 96},
    const {'1': 'CLINICAL_ALLERGY_RECORD', '2': 97},
    const {'1': 'CLINICAL_CONDITION_RECORD', '2': 98},
    const {'1': 'CLINICAL_IMMUNIZATION_RECORD', '2': 99},
    const {'1': 'CLINICAL_LAB_RESULT_RECORD', '2': 100},
    const {'1': 'CLINICAL_MEDICATION_RECORD', '2': 101},
    const {'1': 'CLINICAL_PROCEDURE_RECORD', '2': 102},
    const {'1': 'CLINICAL_VITAL_SIGN_RECORD', '2': 103},
  ],
};

const HealthTypeList$json = const {
  '1': 'HealthTypeList',
  '2': const [
    const {'1': 'types', '3': 1, '4': 3, '5': 14, '6': '.HealthTypes', '10': 'types'},
  ],
};

const HealthDataRequest$json = const {
  '1': 'HealthDataRequest',
  '2': const [
    const {'1': 'type', '3': 1, '4': 1, '5': 14, '6': '.HealthTypes', '10': 'type'},
    const {'1': 'startDate', '3': 2, '4': 1, '5': 9, '10': 'startDate'},
    const {'1': 'endDate', '3': 3, '4': 1, '5': 9, '10': 'endDate'},
    const {'1': 'limit', '3': 4, '4': 1, '5': 5, '10': 'limit'},
  ],
};

const HealthDataRequestList$json = const {
  '1': 'HealthDataRequestList',
  '2': const [
    const {'1': 'requests', '3': 1, '4': 3, '5': 11, '6': '.HealthDataRequest', '10': 'requests'},
  ],
};

const HealthData$json = const {
  '1': 'HealthData',
  '2': const [
    const {'1': 'type', '3': 1, '4': 1, '5': 14, '6': '.HealthTypes', '10': 'type'},
    const {'1': 'objectType', '3': 2, '4': 1, '5': 9, '10': 'objectType'},
    const {'1': 'startDate', '3': 3, '4': 1, '5': 9, '10': 'startDate'},
    const {'1': 'endDate', '3': 4, '4': 1, '5': 9, '10': 'endDate'},
    const {'1': 'device', '3': 5, '4': 1, '5': 9, '10': 'device'},
    const {'1': 'metadata', '3': 6, '4': 1, '5': 9, '10': 'metadata'},
    const {'1': 'count', '3': 7, '4': 1, '5': 3, '10': 'count'},
    const {'1': 'quantityUnit', '3': 8, '4': 1, '5': 9, '10': 'quantityUnit'},
    const {'1': 'quantity', '3': 9, '4': 1, '5': 1, '10': 'quantity'},
    const {'1': 'value', '3': 10, '4': 1, '5': 3, '10': 'value'},
    const {'1': 'totalEnergyBurned', '3': 11, '4': 1, '5': 1, '10': 'totalEnergyBurned'},
    const {'1': 'totalEnergyBurnedUnit', '3': 12, '4': 1, '5': 9, '10': 'totalEnergyBurnedUnit'},
    const {'1': 'totalDistance', '3': 13, '4': 1, '5': 1, '10': 'totalDistance'},
    const {'1': 'totalDistanceUnit', '3': 14, '4': 1, '5': 9, '10': 'totalDistanceUnit'},
    const {'1': 'duration', '3': 15, '4': 1, '5': 1, '10': 'duration'},
    const {'1': 'customValue', '3': 16, '4': 1, '5': 9, '10': 'customValue'},
    const {'1': 'displayName', '3': 17, '4': 1, '5': 9, '10': 'displayName'},
    const {'1': 'fhirResource', '3': 18, '4': 1, '5': 9, '10': 'fhirResource'},
  ],
};

const HealthDataList$json = const {
  '1': 'HealthDataList',
  '2': const [
    const {'1': 'data', '3': 1, '4': 3, '5': 11, '6': '.HealthData', '10': 'data'},
  ],
};

